POST http://140.238.54.136/api/calculateFee
Content-Type: application/json

{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTQwLjIzOC41NC4xMzYvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2ODIzNTI0MDYsImV4cCI6MTY4MjM1MzAwNiwibmJmIjoxNjgyMzUyNDA2LCJqdGkiOiJnV09JN1RFSjExbTNIUklYIiwic3ViIjoiNTFiYzUwZmMwNDJjNDBlOTkxMzdiYjc0NDQ5M2U2MjMiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.Pfyw2uK1cfJ8WYy0JcL3BcLliyVxfZNUG04NrOprVfs",
  "from_district_id":"1600",
  "from_ward_id":"50105",
  "to_district_id":"1600",
  "to_ward_id":"50105",
  "height":"100",
  "length":"100",
  "width":"100",
  "weight":"100"
}
