POST http://140.238.54.136/api/auth/register
Content-Type: application/json

{
  "name": "Đinh Huy Hoàng",
  "email": "20130265@st.hcmuaf.edu.vn",
  "password": "20130265",
  "password_confirmation": "20130265"
}
